env:
  browser: true
  es6: true
  jquery: true
  node: true
extends: 'eslint:recommended'
globals:
  Dargmuesli: false
  grecaptcha: false
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  indent:
     - error
     - 4
     - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-console: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
