version: "3.6"
services:
  apache:
    image: "dargmuesli/randomwinpicker.de"
    deploy:
      replicas: 1
      restart_policy:
        condition: "on-failure"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./dist/randomwinpicker.de:/var/www/randomwinpicker.de"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER_FILE: "/run/secrets/postgres_user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
      POSTGRES_DB_FILE: "/run/secrets/postgres_db"
    secrets:
    - "postgres_user"
    - "postgres_password"
    - "postgres_db"
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
  adminer:
    image: "adminer"
    ports:
    - "8888:8080"
  visualizer:
    image: "dockersamples/visualizer:stable"
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
        - "node.role == manager"
volumes:
  postgres-data: {}
secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_db:
    external: true
